version: '3'  # Docker Compose sürümü

services:  # Hizmetlerin tanımlandığı bölüm
  web:  # Web uygulaması hizmeti
    build: .  # Dockerfile dosyasının bulunduğu dizinden imajın oluşturulması
    ports:  # Port yönlendirmesi
      - "8000:8000"  # Host makinedeki 8000 portunu Docker konteynerindeki 8000 portuna yönlendirme
