# Generated by Django 5.0.3 on 2024-03-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_address_line1_remove_post_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Yayımlanma Tarihi'),
        ),
    ]
